@startuml AppControllerLogic
state "AppControllerLogic State" as ADHDGame_Scenes_AppController_AppControllerLogic_State {
  state "ExitGame" as ADHDGame_Scenes_AppController_AppControllerLogic_State_ExitGame
  state "InGame" as ADHDGame_Scenes_AppController_AppControllerLogic_State_InGame
  state "InitializeGameData" as ADHDGame_Scenes_AppController_AppControllerLogic_State_InitializeGameData
  state "LoadGameData" as ADHDGame_Scenes_AppController_AppControllerLogic_State_LoadGameData
  state "MainMenu" as ADHDGame_Scenes_AppController_AppControllerLogic_State_MainMenu
  state "SettingsMenu" as ADHDGame_Scenes_AppController_AppControllerLogic_State_SettingsMenu
  state "SplashScreen" as ADHDGame_Scenes_AppController_AppControllerLogic_State_SplashScreen
}

ADHDGame_Scenes_AppController_AppControllerLogic_State_InitializeGameData --> ADHDGame_Scenes_AppController_AppControllerLogic_State_InGame : EnterInGame
ADHDGame_Scenes_AppController_AppControllerLogic_State_LoadGameData --> ADHDGame_Scenes_AppController_AppControllerLogic_State_InGame : EnterInGame
ADHDGame_Scenes_AppController_AppControllerLogic_State_MainMenu --> ADHDGame_Scenes_AppController_AppControllerLogic_State_ExitGame : ExitGame
ADHDGame_Scenes_AppController_AppControllerLogic_State_MainMenu --> ADHDGame_Scenes_AppController_AppControllerLogic_State_InitializeGameData : InitializeNewGame
ADHDGame_Scenes_AppController_AppControllerLogic_State_MainMenu --> ADHDGame_Scenes_AppController_AppControllerLogic_State_LoadGameData : LoadGameData
ADHDGame_Scenes_AppController_AppControllerLogic_State_MainMenu --> ADHDGame_Scenes_AppController_AppControllerLogic_State_SettingsMenu : ShowSettingsMenu
ADHDGame_Scenes_AppController_AppControllerLogic_State_SettingsMenu --> ADHDGame_Scenes_AppController_AppControllerLogic_State_MainMenu : ShowMainMenu
ADHDGame_Scenes_AppController_AppControllerLogic_State_SplashScreen --> ADHDGame_Scenes_AppController_AppControllerLogic_State_MainMenu : ShowMainMenu

ADHDGame_Scenes_AppController_AppControllerLogic_State_ExitGame : OnEnter → ExitGame
ADHDGame_Scenes_AppController_AppControllerLogic_State_InitializeGameData : OnEnterHandler() → InitializeGameData
ADHDGame_Scenes_AppController_AppControllerLogic_State_MainMenu : OnEnter → LoadMainMenu
ADHDGame_Scenes_AppController_AppControllerLogic_State_MainMenu : OnExit → UnloadMainMenu
ADHDGame_Scenes_AppController_AppControllerLogic_State_SettingsMenu : OnEnter → LoadSettingsMenu
ADHDGame_Scenes_AppController_AppControllerLogic_State_SettingsMenu : OnExit → UnloadSettingsMenu
ADHDGame_Scenes_AppController_AppControllerLogic_State_SplashScreen : OnEnter → LoadSplashScreen
ADHDGame_Scenes_AppController_AppControllerLogic_State_SplashScreen : OnExit → UnloadSplashScreen

[*] --> ADHDGame_Scenes_AppController_AppControllerLogic_State_SplashScreen
@enduml