@startuml AppControllerLogic
state "AppControllerLogic State" as ADHDGame_Scenes_AppController_AppControllerLogic_State {
  state "InGame" as ADHDGame_Scenes_AppController_AppControllerLogic_State_InGame
  state "LoadGameData" as ADHDGame_Scenes_AppController_AppControllerLogic_State_LoadGameData
  state "MainMenu" as ADHDGame_Scenes_AppController_AppControllerLogic_State_MainMenu
  state "SettingsMenu" as ADHDGame_Scenes_AppController_AppControllerLogic_State_SettingsMenu
  state "SplashScreen" as ADHDGame_Scenes_AppController_AppControllerLogic_State_SplashScreen
  state "StartNewGame" as ADHDGame_Scenes_AppController_AppControllerLogic_State_StartNewGame
}

ADHDGame_Scenes_AppController_AppControllerLogic_State_LoadGameData --> ADHDGame_Scenes_AppController_AppControllerLogic_State_InGame : EnterInGame
ADHDGame_Scenes_AppController_AppControllerLogic_State_MainMenu --> ADHDGame_Scenes_AppController_AppControllerLogic_State_LoadGameData : LoadGameData
ADHDGame_Scenes_AppController_AppControllerLogic_State_MainMenu --> ADHDGame_Scenes_AppController_AppControllerLogic_State_SettingsMenu : ShowSettingsMenu
ADHDGame_Scenes_AppController_AppControllerLogic_State_MainMenu --> ADHDGame_Scenes_AppController_AppControllerLogic_State_StartNewGame : StartNewGame
ADHDGame_Scenes_AppController_AppControllerLogic_State_SettingsMenu --> ADHDGame_Scenes_AppController_AppControllerLogic_State_MainMenu : ShowMainMenu
ADHDGame_Scenes_AppController_AppControllerLogic_State_SplashScreen --> ADHDGame_Scenes_AppController_AppControllerLogic_State_MainMenu : ShowMainMenu
ADHDGame_Scenes_AppController_AppControllerLogic_State_StartNewGame --> ADHDGame_Scenes_AppController_AppControllerLogic_State_InGame : EnterInGame

ADHDGame_Scenes_AppController_AppControllerLogic_State_SplashScreen : OnEnter → ShowSplashScreen

[*] --> ADHDGame_Scenes_AppController_AppControllerLogic_State_SplashScreen
@enduml